export const vegetables={
    title: " Vegetables",
    image1:"assets\vegetables\brinjal.png",
    image2:"assets\vegetables\capsicum.png",
    image3:"assets\vegetables\carrot.png",
    image4:"assets\vegetables\cauliflower.png",
    image5:"assets\vegetables\chilli.png",
    image6:"assets\vegetables\ladys finger.png",
    image7:"assets\vegetables\onions.png",
    image8:"assets\vegetables\potatoes.png",
    image9:"assets\vegetables\pumpkin.png",
    image10:"assets\vegetables\tomato.png",
    price1: "55 INR",
    price2: "88 INR",
    price3: "32 INR",
    price4: "45 INR",
    price5: "76 INR",
    price6: "87 INR",
    price7: "98 INR",
    price8: "56 INR",
    price9: "50 INR",
    price10: "58 INR"
    }
    export const fruits={
    title: "Fruits",
    image1:"assets\fruits\apples.png",
    image2:"assets\fruits\banana.png",
    image3:"assets\fruits\grapes.png",
    image4:"assets\fruits\guava.png",
    image5:"assets\fruits\mangoes.png",
    image6:"assets\fruits\orange.png",
    image7:"assets\fruits\palm fruit.png",
    image8:"assets\fruits\papaya.png",
    image9:"assets\fruits\pineapple.png",
    image10:"assets\fruits\pomogranate.png",
    image11:"assets\fruits\strawberry.png",
    image12:"assets\fruits\watermelon.png",
    price1: "55 INR",
    price2: "88 INR",
    price3: "32 INR",
    price4: "45 INR",
    price5: "76 INR",
    price6: "87 INR",
    price7: "98 INR",
    price8: "56 INR",
    price9: "50 INR",
    price10: "58 INR",
    price11: "12 INR",
    price12: "34 INR"
    }
    
    export const detergents={
    title: "Detergent",
    image1:"assets\detergents\Ariel.png",
    image2:"assets\detergents\comfort.png",
    image3:"assets\detergents\softouch.png",
    image4:"assets\detergents\surfexcel.png",
    image5:"assets\detergents\tide.png",
    image6:"assets\detergents\washing powder.png",
    price1: "55 INR",
    price2: "88 INR",
    price3: "32 INR",
    price4: "45 INR",
    price5: "76 INR",
    price6: "87 INR"
    }

    export const soaps = {
    title: "Soaps& Shampoo",
    image1: "assets\soaps\head&shoulder.png",
    image2: "assets\soaps\herbal.png",
    image3: "assets\soaps\himalaya.png",
    image4: "assets\soaps\lux.png",
    image5: "assets\soaps\pears.png",
    image6: "assets\soaps\santoor.png",
    image7: "assets\soaps\vatika.png",
    price1: "55 INR",
    price2: "88 INR",
    price3: "32 INR",
    price4: "45 INR",
    price5: "76 INR",
    price6: "87 INR",
    price7: "66 INR"
    }